-->a
SELECT NU_IMPO, 
	ROUND(CASE CO_MONE
	  WHEN 'SOL' THEN IM_ARGU_ORIG / FA_CAMB 
	  ELSE IM_ARGU_ORIG / 1 
	END,2) AS IM_CALC_USD,
TI_DOCU_TESO, NU_DOCU_TESO, IM_ARGU_ORIG, FA_CAMB_BASE, ROUND(IM_ARGU_ORIG * FA_CAMB_BASE, 2) IM_CALC_PEN, IM_ARGU_NACI, FA_CAMB_BASE, * 
FROM TDSEGU_ARGU 
WHERE NU_IMPO = '888B' ORDER BY NU_SECU

-->b
SELECT NU_IMPO, CO_ITEM, CA_IMPO, IM_UNIT,  (CA_IMPO * IM_UNIT) IM_MATE_OC, 
(
	SELECT SUM(CA_IMPO * IM_UNIT) IM_TOT_OC
	FROM TDIMPT_ORCO WHERE NU_IMPO = IM.NU_IMPO
	GROUP BY NU_IMPO
) IM_TOT_OC
FROM TDIMPT_ORCO IM 
WHERE NU_IMPO = '888B'

-->c
SELECT CO_LOTE, CO_ITEM, NU_DOCU, TI_DOCU, CO_UNME_MOVI, CA_DOCU_MOVI, IM_COST_ALAL, CA_DOCU_MOVI * IM_COST_ALAL UNITARIO_CALCULADO , IM_COTO_ALMA, IM_COTO_ALAL
FROM TDDOCU_ALMA
WHERE TI_SITU = 'ACT' 
AND NU_DOCU = '0001-0000003803'
AND CO_LOTE = '888B'
AND TI_DOCU IN ('ITP','STP')
AND NOT TI_DOCU IN ('ITR','STR')

-->d 
SELECT CO_ITEM name, YEAR(C.FE_DOCU) year,  CA_DOCU units, PR_VENT price
FROM OFIVENT..TCDOCU_CLIE C  INNER JOIN OFIVENT..TDDOCU_CLIE D
ON C.TI_DOCU = D.TI_DOCU AND C.NU_DOCU = D.NU_DOCU
WHERE YEAR(C.FE_DOCU) = 2013
AND C.TI_DOCU = 'FAC'
AND NOT C.CO_ESTA_DOCU = 'ANU'
AND D.CO_ITEM = '101423'
AND D.CO_LOTE = '888B'
